// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbKFtoL_H8UEg3dNXHEPOgvSDWtHXAOPg',
    appId: '1:657584084120:web:4c8c22f274739f6bb8eced',
    messagingSenderId: '657584084120',
    projectId: 'mindcare-diary',
    authDomain: 'mindcare-diary.firebaseapp.com',
    storageBucket: 'mindcare-diary.firebasestorage.app',
    measurementId: 'G-6E3W9DT5TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk2hleM5h78FRHiRPYqbn0xB1OJB--MBs',
    appId: '1:657584084120:android:645fa3a2ac9bfe79b8eced',
    messagingSenderId: '657584084120',
    projectId: 'mindcare-diary',
    storageBucket: 'mindcare-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ybJelZjvQc7t1k0mjrvUee5VbwmHnlY',
    appId: '1:657584084120:ios:2762d273552c76dab8eced',
    messagingSenderId: '657584084120',
    projectId: 'mindcare-diary',
    storageBucket: 'mindcare-diary.firebasestorage.app',
    iosBundleId: 'com.mindcare.mindcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ybJelZjvQc7t1k0mjrvUee5VbwmHnlY',
    appId: '1:657584084120:ios:2762d273552c76dab8eced',
    messagingSenderId: '657584084120',
    projectId: 'mindcare-diary',
    storageBucket: 'mindcare-diary.firebasestorage.app',
    iosBundleId: 'com.mindcare.mindcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbKFtoL_H8UEg3dNXHEPOgvSDWtHXAOPg',
    appId: '1:657584084120:web:f165281dc16b27a0b8eced',
    messagingSenderId: '657584084120',
    projectId: 'mindcare-diary',
    authDomain: 'mindcare-diary.firebaseapp.com',
    storageBucket: 'mindcare-diary.firebasestorage.app',
    measurementId: 'G-J7RQCVT3P1',
  );
}
